### ISSUE TITLE
unresolved symbols when linking hello_pass.so 

### ISSUE THREAD

**Issue by AntonBikineev** [eliben/llvm-clang-samples#16]
```Undefined symbols for architecture x86_64:
  "llvm::raw_ostream::write_escaped(llvm::StringRef, bool)", referenced from:
      HelloFuncs::runOnFunction(llvm::Function&) in hello_pass-05c8d0.o
  "llvm::raw_ostream::write(char const*, unsigned long)", referenced from:
      llvm::raw_ostream::operator<<(llvm::StringRef) in hello_pass-05c8d0.o
  "llvm::raw_ostream::write(unsigned char)", referenced from:
      llvm::raw_ostream::operator<<(char) in hello_pass-05c8d0.o```

I resolved it changing LLVM_LDFLAGS_NOLIBS to LLVM_LDFLAGS

**Comment by eliben** [comment]
I can't reproduce the problem. What's your machine & build setup?

**Comment by kirbyfan64** [comment]
Last time something like this happened to me (`Undefined symbols for architecture x86_64`), it was actually because I was using libraries that were 32-bit on my 64-bit computer.

**Comment by ob** [comment]
I have the same problem as @AntonBikineev. I also solved it the same way, by applying the following patch:

```diff --git a/Makefile b/Makefile
index 7110840..c987686 100644
--- a/Makefile
+++ b/Makefile
@@ -49,7 +49,7 @@ $(info -----------------------------------------------)
 # Note: starting with release 3.7, llvm-config will inject flags that gcc may
 # not support (for example '-Wcovered-switch-default'). If you run into this
 # problem, build with CXX set to a modern clang++ binary instead of g++.
-CXX := g++
+CXX := clang++
 CXXFLAGS := -fno-rtti -O0 -g
 PLUGIN_CXXFLAGS := -fpic

@@ -158,7 +158,7 @@ $(BUILDDIR)/bb_toposort_sccs: $(SRC_LLVM_DIR)/bb_toposort_sccs.cpp

 $(BUILDDIR)/hello_pass.so: $(SRC_LLVM_DIR)/hello_pass.cpp
        $(CXX) $(PLUGIN_CXXFLAGS) $(CXXFLAGS) $(LLVM_CXXFLAGS) \
-               $^ $(PLUGIN_LDFLAGS) $(LLVM_LDFLAGS_NOLIBS) -o $@
+               $^ $(PLUGIN_LDFLAGS) $(LLVM_LDFLAGS) -o $@

 $(BUILDDIR)/clang-check: $(SRC_CLANG_DIR)/ClangCheck.cpp
        $(CXX) $(CXXFLAGS) $(LLVM_CXXFLAGS) $(CLANG_INCLUDES) $^ \```

Not sure what that's about... but I can help debug. I'm on OS X Yosemite 10.10.5. I built llvm/clang as of today (from git) using ninja.

**Comment by ob** [comment]
I also had to remove the --start-group and --end-group from the linker's flags.

**Comment by eliben** [comment]
@ob, what OS and gcc/clang versions do you have?

**Comment by ob** [comment]
I checked out llvm from github:

    dirac llvm $ git log -1
    commit 18329ced975b85fbcf34aaa928e5d66fe8da8282
    Author: Reid Kleckner <rnk@google.com>
    Date:   Tue Sep 8 23:28:38 2015 +0000
    
        [WinEH] Avoid creating MBBs for LLVM BBs that cannot contain code
    
        Typically these are catchpads, which hold data used to decide whether to
        catch the exception or continue unwinding. We also shouldn't create MBBs
        for catchendpads, cleanupendpads, or terminatepads, since no real code
        can live in them.
    
        This fixes a problem where MI passes (like the register allocator) would
        try to put code into catchpad blocks, which are not executed by the
        runtime. In the new world, blocks ending in invokes now have many
        possible successors.
    
        git-svn-id: https://llvm.org/svn/llvm-project/llvm/trunk@247102 91177308-0d34-0410-b5e6-96231b3b80d8
    

    dirac llvm $ uname -a
    Darwin dirac.bitkeeper.com 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
    
    dirac llvm $ sw_vers
    ProductName:	Mac OS X
    ProductVersion:	10.10.5
    BuildVersion:	14F27
    
    dirac llvm-clang-samples $ clang --version
    Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
    Target: x86_64-apple-darwin14.5.0
    Thread model: posix
    dirac llvm-clang-samples $ make 
    -----------------------------------------------
    Using LLVM_SRC_PATH = $HOME/projects/llvm/llvm
    Using LLVM_BUILD_PATH = $HOME/projects/llvm/llvm-build
    Using LLVM_BIN_PATH = $HOME/projects/llvm/llvm-build/bin
    -----------------------------------------------
    clang++ -fno-rtti -O0 -g `$HOME/projects/llvm/llvm-build/bin/llvm-config --cxxflags` src_llvm/bb_toposort_sccs.cpp `$HOME/projects/llvm/llvm-build/bin/llvm-config --ldflags --libs --system-libs` -o build/bb_toposort_sccs
    clang++ -fno-rtti -O0 -g `$HOME/projects/llvm/llvm-build/bin/llvm-config --cxxflags` src_llvm/simple_module_pass.cpp `$HOME/projects/llvm/llvm-build/bin/llvm-config --ldflags --libs --system-libs` -o build/simple_module_pass
    clang++ -fno-rtti -O0 -g `$HOME/projects/llvm/llvm-build/bin/llvm-config --cxxflags` src_llvm/simple_bb_pass.cpp `$HOME/projects/llvm/llvm-build/bin/llvm-config --ldflags --libs --system-libs` -o build/simple_bb_pass
    clang++ -fno-rtti -O0 -g `$HOME/projects/llvm/llvm-build/bin/llvm-config --cxxflags` src_llvm/analyze_geps.cpp `$HOME/projects/llvm/llvm-build/bin/llvm-config --ldflags --libs --system-libs` -o build/analyze_geps
    clang++ -fno-rtti -O0 -g `$HOME/projects/llvm/llvm-build/bin/llvm-config --cxxflags` src_llvm/jit_orc_run.cpp `$HOME/projects/llvm/llvm-build/bin/llvm-config --ldflags --libs --system-libs` -o build/jit_orc_run
    clang++ -fpic -fno-rtti -O0 -g `$HOME/projects/llvm/llvm-build/bin/llvm-config --cxxflags` \
    		src_llvm/hello_pass.cpp -shared `$HOME/projects/llvm/llvm-build/bin/llvm-config --ldflags` -o build/hello_pass.so
    Undefined symbols for architecture x86_64:
      "llvm::raw_ostream::write_escaped(llvm::StringRef, bool)", referenced from:
          HelloFuncs::runOnFunction(llvm::Function&) in hello_pass-a40f87.o
      "llvm::raw_ostream::write(char const*, unsigned long)", referenced from:
          HelloFuncs::runOnFunction(llvm::Function&) in hello_pass-a40f87.o
      "llvm::raw_ostream::write(unsigned char)", referenced from:
          HelloFuncs::runOnFunction(llvm::Function&) in hello_pass-a40f87.o
      "llvm::FunctionPass::assignPassManager(llvm::PMStack&, llvm::PassManagerType)", referenced from:
          vtable for HelloFuncs in hello_pass-a40f87.o
      "llvm::PassRegistry::registerPass(llvm::PassInfo const&, bool)", referenced from:
          __GLOBAL__sub_I_hello_pass.cpp in hello_pass-a40f87.o
      "llvm::PassRegistry::getPassRegistry()", referenced from:
          __GLOBAL__sub_I_hello_pass.cpp in hello_pass-a40f87.o
      "llvm::Pass::releaseMemory()", referenced from:
          vtable for HelloFuncs in hello_pass-a40f87.o
      "llvm::Pass::dumpPassStructure(unsigned int)", referenced from:
          vtable for HelloFuncs in hello_pass-a40f87.o
      "llvm::Pass::getAsImmutablePass()", referenced from:
          vtable for HelloFuncs in hello_pass-a40f87.o
      "llvm::Pass::getAsPMDataManager()", referenced from:
          vtable for HelloFuncs in hello_pass-a40f87.o
      "llvm::Pass::preparePassManager(llvm::PMStack&)", referenced from:
          vtable for HelloFuncs in hello_pass-a40f87.o
      "llvm::Pass::getAdjustedAnalysisPointer(void const*)", referenced from:
          vtable for HelloFuncs in hello_pass-a40f87.o
      "llvm::Pass::~Pass()", referenced from:
          HelloFuncs::~HelloFuncs() in hello_pass-a40f87.o
          HelloFuncs::~HelloFuncs() in hello_pass-a40f87.o
      "llvm::outs()", referenced from:
          HelloFuncs::runOnFunction(llvm::Function&) in hello_pass-a40f87.o
      "llvm::FunctionPass::createPrinterPass(llvm::raw_ostream&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
          vtable for HelloFuncs in hello_pass-a40f87.o
      "llvm::FunctionPass::getPotentialPassManagerType() const", referenced from:
          vtable for HelloFuncs in hello_pass-a40f87.o
      "llvm::Pass::getPassName() const", referenced from:
          vtable for HelloFuncs in hello_pass-a40f87.o
      "llvm::Pass::verifyAnalysis() const", referenced from:
          vtable for HelloFuncs in hello_pass-a40f87.o
      "llvm::Pass::print(llvm::raw_ostream&, llvm::Module const*) const", referenced from:
          vtable for HelloFuncs in hello_pass-a40f87.o
      "llvm::Value::getName() const", referenced from:
          HelloFuncs::runOnFunction(llvm::Function&) in hello_pass-a40f87.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [build/hello_pass.so] Error 1
    dirac llvm-clang-samples $ 
    
On Sep 9, 2015, at 7:22 AM, Eli Bendersky <notifications@github.com> wrote:

@ob, what OS and gcc/clang versions do you have?

**Comment by eliben** [comment]
Ah, you're on OS X. Please note that I only *officially* support it for Linux. I don't have access to a development OS X machine.

I'll create a tag that will make OS-X related issues easier to find, hopefully this will help folks find solutions for their systems.

**Comment by ob** [comment]
So I managed to make it compile without errors (by tweaking the Makefile), but
now I get some failures in the test suite. I can make my changes dependent on which
OS you’re running it on and send you a patch, but I’d like to fix the test failures
first. Any ideas what those are about before I spend a bunch of time chasing them?

dirac llvm-clang-samples $ make test
-----------------------------------------------
Using LLVM_SRC_PATH = $HOME/projects/llvm/llvm
Using LLVM_BUILD_PATH = $HOME/projects/llvm/build
Using LLVM_BIN_PATH = $HOME/projects/llvm/build/bin
-----------------------------------------------
python3 test/all_tests.py
.....FFF.....
======================================================================
FAIL: test_hello_on_fact (test_hello_pass_plugin.TestHelloPassPlugin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ob/projects/llvm/llvm-clang-samples/test/test_hello_pass_plugin.py", line 12, in test_hello_on_fact
    OUTPUT_HELLO_FUNCS)
  File "/Users/ob/projects/llvm/llvm-clang-samples/test/tools.py", line 70, in assertOptPluginOutput
    self.assertEqual(rc, 0)
AssertionError: 1 != 0

======================================================================
FAIL: test_bar (test_jit_orc_run.TestJITOrcRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ob/projects/llvm/llvm-clang-samples/test/test_jit_orc_run.py", line 21, in test_bar
    OUTPUT_TWODOUBLEFOO_BAR)
  File "/Users/ob/projects/llvm/llvm-clang-samples/test/tools.py", line 59, in assertSampleOutput
    self.assertEqual(rc, 0)
AssertionError: -6 != 0

======================================================================
FAIL: test_foo (test_jit_orc_run.TestJITOrcRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ob/projects/llvm/llvm-clang-samples/test/test_jit_orc_run.py", line 17, in test_foo
    OUTPUT_TWODOUBLEFOO_FOO)
  File "/Users/ob/projects/llvm/llvm-clang-samples/test/tools.py", line 59, in assertSampleOutput
    self.assertEqual(rc, 0)
AssertionError: -6 != 0

----------------------------------------------------------------------
Ran 13 tests in 2.759s

FAILED (failures=3)
make: *** [test] Error 1

**Comment by ob** [comment]
FWIW, https://github.com/eliben/llvm-clang-samples/pull/11 mostly solves all these issues. If you don't want to integrate it, it'd be nice to at least put a link to it in the README or have the Makefile fail if it's running on OS X. 

I'm still not 100% there, now I have two tests failing: 

    ======================================================================
    FAIL: test_bar (test_jit_orc_run.TestJITOrcRun)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Users/ob/projects/llvm/llvm-clang-samples/test/test_jit_orc_run.py", line 21, in test_bar
        OUTPUT_TWODOUBLEFOO_BAR)
      File "/Users/ob/projects/llvm/llvm-clang-samples/test/tools.py", line 61, in assertSampleOutput
        self.assertEqual(rc, 0)
    AssertionError: -6 != 0
    
    ======================================================================
    FAIL: test_foo (test_jit_orc_run.TestJITOrcRun)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Users/ob/projects/llvm/llvm-clang-samples/test/test_jit_orc_run.py", line 17, in test_foo
        OUTPUT_TWODOUBLEFOO_FOO)
      File "/Users/ob/projects/llvm/llvm-clang-samples/test/tools.py", line 61, in assertSampleOutput
        self.assertEqual(rc, 0)
    AssertionError: -6 != 0
    
    ----------------------------------------------------------------------

    dirac llvm-clang-samples $ build/jit_orc_run bar inputs/twodoublefoo.ll
    
    Assertion failed: (TM.isCompatibleDataLayout(getDataLayout()) && "Can't create a MachineFunction using a Module with a " "Target-incompatible DataLayout attached\n"), function MachineFunction, file /Users/ob/projects/llvm/llvm/lib/CodeGen/MachineFunction.cpp, line 93.
    Abort trap: 6

**Comment by unphased** [comment]
I am also seeing the OS X test failures

**Comment by DaoWen** [comment]
I'm also running on OS X. The patch in #11 was very helpful. It would be really great if it were merged. I also see the same two test failures. I noticed that they're both JIT-related. Since I'm not using any features related to JIT compilation, I haven't been too worried about those tests failing.

**Comment by neko1990** [comment]
@ob The JIT try to find entry for _foo/_bar in readed llvm module. Either regenerate twodoublefoo.ll ( `clang -cc1 twodoublefoo.c -emit-llvm` ) or modify .ll file manually by adding "_" to foo/bar ( `define double @_foo(double %a, double %b) #0` ) would pass the jit_orc_run test.
